[GENERAL]
SIMILARITY_MEASURE = "cosine"
KEEP_ALIVE = "5m"

[MODELS]
OPENAI = { API_KEY = "", API_URL = "" }
GROQ = { API_KEY = "" }
ANTHROPIC = { API_KEY = "" }
GEMINI = { API_KEY = "" }
DEEPSEEK = { API_KEY = "" }
OLLAMA = { API_URL = "" }

[MODELS.CUSTOM_OPENAI]
API_KEY = ""
API_URL = ""
MODEL_NAME = ""

[API_ENDPOINTS]
SEARXNG = ""
